[convert_bool]
overview = """
Converts a [`bool`] to [`uint`] losslessly.
The resulting value is `0` for `false` and `1` for `true` values.

[`uint`]: struct@crate::uint
"""
examples = """
assert_eq!(uint::from(true), uint!(1));
assert_eq!(uint::from(false), uint!(0));
"""
