[BITS]
overview = """
The size of this integer type in bits.
"""
examples = """
assert_eq!(uint::BITS, %SIZE_BITS%);
"""

[MAX]
overview = """
The largest value that can be represented by this integer type. (2<sup>%SIZE_BITS%</sup> &minus; 1).
"""
examples = """
assert_eq!(uint::MAX, uint!(%MAX_VALUE%));
"""

[MIN]
overview = """
The smallest value that can be represented by this integer type.
"""
examples = """
assert_eq!(uint::MIN, uint!(%MIN_VALUE%));
"""
