[package]
name = "mkdocs"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
readme = "README.md"
publish = false

[dependencies]
aho-corasick = { version = "1.1" }
basic-toml = { version = "0.1" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
