[BITS]
overview = """
The size of this integer type in bits.
"""
examples = """
assert_eq!(uint::BITS, $bits);
"""

[MAX]
overview = """
The largest value that can be represented by this integer type. (2<sup>$bits</sup> &minus; 1).
"""
examples = """
assert_eq!(uint::MAX, uint!($uint_max));
"""

[MIN]
overview = """
The smallest value that can be represented by this integer type.
"""
examples = """
assert_eq!(uint::MIN, uint!($uint_min));
"""
