[convert_bool]
overview = """
Converts a [`bool`] to [`int`] losslessly.
The resulting value is `0` for `false` and `1` for `true` values.

[`int`]: struct@crate::int
"""
examples = """
assert_eq!(int::from(true), int!(1));
assert_eq!(int::from(false), int!(0));
"""
