[BITS]
overview = """
The size of this integer type in bits.
"""
examples = """
assert_eq!(int::BITS, %SIZE_BITS%);
"""

[MAX]
overview = """
The largest value that can be represented by this integer type. (2<sup>(%SIZE_BITS% &minus; 1)</sup> &minus; 1).
"""
examples = """
assert_eq!(int::MAX, int!(%MAX_VALUE%));
"""

[MIN]
overview = """
The smallest value that can be represented by this integer type.
"""
examples = """
assert_eq!(int::MIN, int!(%MIN_VALUE%));
"""
