[alias]
mkdocs = "run --release --manifest-path tools/mkdocs/Cargo.toml"

[build]
rustdocflags = [
  "--default-theme", "dark",
  "--cfg", "docsrs",
]
rustflags = [
  "-C", "llvm-args=--unroll-threshold=1024",
]
