[unbounded_shl]
overview = """
Unbounded shift left. Computes `self << rhs`, without bounding the value of `rhs`.

If `rhs` is larger or equal to the number of bits in `self`,
the entire value is shifted out, and `0` is returned.
"""
examples = """
assert_eq!(int!(0x1).unbounded_shl(4), int!(0x10));
assert_eq!(int!(0x1).unbounded_shl(129), int!(0));
"""

[unbounded_shr]
overview = """
Unbounded shift right. Computes `self >> rhs`, without bounding the value of `rhs`.

If `rhs` is larger or equal to the number of bits in `self`,
the entire value is shifted out, which yields `0` for a positive number,
and `-1` for a negative number.
"""
examples = """
assert_eq!(int!(0x10).unbounded_shr(4), int!(0x1));
assert_eq!(int!(0x10).unbounded_shr(129), int!(0));
assert_eq!(int::MIN.unbounded_shr(129), int!(-1));
"""
