[unchecked_add]
overview = """
Unchecked integer addition. Computes `self + rhs`,
assuming overflow cannot occur.

Calling `x.unchecked_add(y)` is semantically equivalent to calling
`x.`[`checked_add`]`(y).`[`unwrap_unchecked`]`()`.

If you're just trying to avoid the panic in debug mode, then **do not** use
this. Instead, you're looking for [`wrapping_add`].

# Safety

This results in undefined behavior when `self + rhs > int::MAX` or
`self + rhs < int::MIN`, i.e. when [`checked_add`] would return `None`.

[`checked_add`]: Self::checked_add
[`wrapping_add`]: Self::wrapping_add
[`unwrap_unchecked`]: Option::unwrap_unchecked
"""

[unchecked_sub]
overview = """
Unchecked integer subtraction. Computes `self - rhs`,
assuming overflow cannot occur.

Calling `x.unchecked_sub(y)` is semantically equivalent to calling
`x.`[`checked_sub`]`(y).`[`unwrap_unchecked`]`()`.

If you're just trying to avoid the panic in debug mode, then **do not** use
this. Instead, you're looking for [`wrapping_sub`].

# Safety

This results in undefined behavior when `self - rhs > int::MAX` or
`self - rhs < int::MIN`, i.e. when [`checked_sub`] would return `None`.

[`checked_sub`]: Self::checked_sub
[`wrapping_sub`]: Self::wrapping_sub
[`unwrap_unchecked`]: Option::unwrap_unchecked
"""

[unchecked_mul]
overview = """
Unchecked integer multiplication. Computes `self * rhs`,
assuming overflow cannot occur.

Calling `x.unchecked_mul(y)` is semantically equivalent to calling
`x.`[`checked_mul`]`(y).`[`unwrap_unchecked`]`()`.

If you're just trying to avoid the panic in debug mode, then **do not** use
this. Instead, you're looking for [`wrapping_mul`].

# Safety

This results in undefined behavior when `self * rhs > int::MAX` or
`self * rhs < int::MIN`, i.e. when [`checked_mul`] would return `None`.

[`checked_mul`]: Self::checked_mul
[`wrapping_mul`]: Self::wrapping_mul
[`unwrap_unchecked`]: Option::unwrap_unchecked
"""

[unchecked_shl]
overview = """
Unchecked shift left. Computes `self << rhs`,
assuming that `rhs` is less than the number of bits in `self`.

# Safety

This results in undefined behavior if `rhs` is larger than or equal to the
number of bits in `self`, i.e. when [`checked_shl`] would return `None`.

[`checked_shl`]: Self::checked_shl
"""

[unchecked_shr]
overview = """
Unchecked shift right. Computes `self >> rhs`,
assuming that `rhs` is less than the number of bits in `self`.

# Safety

This results in undefined behavior if `rhs` is larger than or equal to the
number of bits in `self`, i.e. when [`checked_shr`] would return `None`.

[`checked_shr`]: Self::checked_shr
"""

[unchecked_neg]
overview = """
Unchecked negation. Computes `-self`, assuming overflow cannot occur.

# Safety

This results in undefined behavior when `self == int::MIN`, i.e. when
[`checked_neg`] would return `None`.

[`checked_neg`]: Self::checked_neg
"""
